{% set name = "opencensus-proto" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opencensus-proto-{{ version }}.tar.gz
  sha256: 963e4524fef4596482581d3cff0943f68839c7c33a56cdf20967672175ed25bc

build:
  number: 1
  noarch: python
  script: 
    - echo "__version__ = '{{ version }}'" > version.py
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - grpcio >=1.0.0,<2.0.0
    - python >={{ python_min }}

test:
  imports:
    - opencensus
    - opencensus.proto
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/census-instrumentation/opencensus-proto/tree/master/gen-python
  summary: OpenCensus Proto
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
